### ISSUE TITLE
Implementations TODO

### ISSUE THREAD

**Issue by ezzatron** [ezzatron/nvector-js#9]
- [x] `n_EB_E2p_EB_E`
- [x] `p_EB_E2n_EB_E`
- [x] `n_EA_E_and_n_EB_E2p_AB_E`
- [x] `n_EA_E_and_p_AB_E2n_EB_E `
- [x] `n_E2R_EN`
- [x] `R2xyz`
- [x] `R2zyx`
- [x] `xyz2R`
- [x] `zyx2R`
- [x] `n_E_and_wa2R_EL`
- [x] `R_EL2n_E`
- [x] `R_EN2n_E`
